### ISSUE TITLE
hi，the example can not work in v3.0.*

### ISSUE THREAD

**Issue by deatil** [phpseclib/phpseclib#1597]
https://github.com/phpseclib/phpseclib/blob/b296d4a88b41dca4bbdfde2980c1234563751344/phpseclib/Crypt/AES.php#L28

i use the example，but can not work.

now, i just use this what can work.

~~~
        $aes = new AES($this->mode);
        $aes->setIV($this->iv);
        $aes->setKey($key);
        $encodeData = $aes->encrypt($plaintext);
~~~

i see some code from v2, v3'code has changed.

**Comment by terrafrost** [comment]
It works fine for me:

```php
<?php
require __DIR__ . '/vendor/autoload.php';

use phpseclib3\Crypt\AES;

$aes = new AES('ctr');
$aes->setIV(random_bytes(16));
$aes->setKey(random_bytes(16));
echo bin2hex($aes->encrypt('hello, world!'));
```
What do you mean when you say "but can not work"? Do you get an exception? If so what does the exception say?

**Comment by deatil** [comment]
> It works fine for me:
> 
> ```
> <?php
> require __DIR__ . '/vendor/autoload.php';
> 
> use phpseclib3\Crypt\AES;
> 
> $aes = new AES('ctr');
> $aes->setIV(random_bytes(16));
> $aes->setKey(random_bytes(16));
> echo bin2hex($aes->encrypt('hello, world!'));
> ```
> 
> What do you mean when you say "but can not work"? Do you get an exception? If so what does the exception say?

The code what you give example is good for me.

I use the AES class file example and i will get an exception 

~~~php
Too few arguments to function phpseclib3\\Crypt\\Rijndael::__construct(), 0 passed in `lib path`
~~~

I see v2'code and the v2'code has a default `mode` but v3'code don't set the default  `mode`. Now v3'example need change to hava right code. And v2'code don't set iv but v3'code need set mode, i don't understand why?

**Comment by terrafrost** [comment]
PHP has changed a lot since phpseclib v1 was released (v2 is basically v1 but namespaced). From what I've seen the general trend has been to discourage the use of cryptographic primitives. When you let people choose what encryption algorithms they want to use and the parameters to use with them they'll often make poor choices. Like mcrypt and OpenSSL let you chose the algorithm (even bad ones). mcrypt would silently NULL-pad keys that were too short to the correct length and even tho mcrypt stopped NULL-padding keys in 5.6 it still NULL-padded plaintext's for block cipher modes that required the plaintext be a multiple of the block size (eg. cbc mode).

Contrast this with libsodium. libsodium doesn't let you chose encryption algorithms. All the bad choices are taken away from you. In some cases libsodium basically acts as a pseudo cryptographic protocol instead of a cryptographic primitive. Like with mcrypt or OpenSSL AEAD was optional. If you wanted to do it you'd have to manually combine the cryptographic primitives yourself but in so doing you could do it incorrectly. You could do encrypt-and-mac, mac-then-encrypt or encrypt-then-mac. The best choice is the last one but if you're even doing AEAD it's something you could super easily mess up on.

In acknowledgement of that trend and to stave off criticism, phpseclib v3 has removed the defaults, to make symmetric key encryption harder to use. To discourage _casual_ and _uninformed_ use.

If you want to NULL-pad your key you can still do so but phpseclib v3 will no longer do so for you. This takes the onus off of phpseclib to do anything and places the onus on the devs using phpseclib v3 to do stuff.

**Comment by terrafrost** [comment]
For v4 I want to make working with X.509 certs waaay easier. So I still want to make things easier to use - just not cryptographic primitives.

**Comment by deatil** [comment]
> For v4 I want to make working with X.509 certs waaay easier. So I still want to make things easier to use - just not cryptographic primitives.

good.

**Comment by terrafrost** [comment]
I've updated the examples as well:

https://github.com/phpseclib/phpseclib/commit/a18b86ae266fcb0c198ac0446b97bc6a5f521444

Thanks!
